### ISSUE TITLE
CASE Questions

### ISSUE THREAD

**Issue by Robbo1234** [WeConnect/case-apps#5]
Great work,

I've a few questions:

Is Case.Subs.Xyzcopy missing from App Set #2 installer? 
Is there a likelihood that App Set #3 going to be added to future installer?
Is there going to be installer for Revit 2014 / 2017?
Also I noticed that "Exceler8 Export Schedule" doesn't export schedule id's and Type/Instance property headings. This means you'll can't import back in via "Exceler8 Import(Sync)".
btw "Exceler8 Export Category" works fine.

Thanking you all in a advance

Regards

Rob

**Comment by DuncanLithgow** [comment]
It's not at all clear how CASE (now part of We-work) will be part of this project, they seem to be saying that they as we-work won't be. So I guess there will only be real changes to the code if we can create a community around this project.

**Comment by Robbo1234** [comment]
Hi Don,

Totally appropriate all your great work in provide the addins.

But has Revit 2015 and 2016 Case Apps been tested before being released because it's a real pity that the powerful  Exceler8 Export Schedule doesn't work plus I would really love to get the App Set #3 added to future Revit 2015 and 2016  installer. 

Also is the any user CASE addin documentation/ tutorials on the use of these addin available?

Regards
Rob

**Comment by rudderdon** [comment]
Feel free to build the installer as you think it should be built and submit a pull request. Since Revit add-in installations are really nothing more than a file copy, this is often not necessary - we'll leave this up to the community. The schedule export feature was abandoned many moons ago since Revit provides a txt schedule export tool in the base functionality of Revit. Feel free to flesh that feature out and submit a pull request and we'll review it.

All documentation is gone and won't come back unless the community provides it. We'll monitor and manage pull requests as they come in.

**Comment by Robbo1234** [comment]
Thanks Don

**Comment by Robbo1234** [comment]
Is there a workflow to install the Apps Set #3 which were not included in the installer? #5
Thanks
